#only focus on two classes: 0 and 1
name: UNet_hedataset
model:
  type: UNet
  num_classes: 2

train:
  learning_rate: 0.001
  batch_size: 4
  num_epochs: 100
  early_stop: 15
  save_interval: 1

lr_scheduler:
  args:
    patience: 3
    factor: 0.1

optimizer:
  type: Adam
  args:
    lr: 0.0001
    weight_decay: 0.0001

val:  
  batch_size: 1
  view_cnt: 2

data:
  data_dir: "/dssg/home/acct-zhaochaoxian/zhaochaoxian-user1/he_dataset/dataset/pred2/patch"
  train_ratio: 0.7

output_dir: 
  model: models
  log: logs
