name: UNet_pannuke_SGD_2
model:
  type: UNet
  num_classes: 6

train:
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 100
  early_stop: 15
  save_interval: 1

lr_scheduler:
  args:
    patience: 3
    factor: 0.1

optimizer:
  type: SGD
  args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001

val:  
  batch_size: 1
  view_cnt: 10

data:
  data_dir: "/dssg/home/acct-zhaochaoxian/zhaochaoxian-user1/SemanticSegmentation/ExternalData"
  train_ratio: 0.8

output_dir: 
  model: models
  log: logs
